--create a database & schema
CREATE DATABASE TIMETRAVEL_EXERCISE;
CREATE SCHEMA TIMETRAVEL_EXERCISE.COMPANY_X;

--create a customer table
CREATE TABLE TIMETRAVEL_EXERCISE.COMPANY_X.CUSTOMER AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
LIMIT 500;

--drop the schema(assuming it happened by accident)
DROP SCHEMA TIMETRAVEL_EXERCISE.COMPANY_X;

--verify table doesn't exist anymore
select * from TIMETRAVEL_EXERCISE.COMPANY_X.CUSTOMER;

--undrop schema
UNDROP SCHEMA TIMETRAVEL_EXERCISE.COMPANY_X;
