SELECT 

AVG(PS_SUPPLYCOST) AS PS_SUPPLYCOST_AVG,

AVG(PS_AVAILQTY) AS PS_AVAILQTY_AVG,

MAX(PS_COMMENT) AS PS_COMMENT_MAX

FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PARTSUPP;

--materialised view

CREATE OR REPLACE MATERIALIZED VIEW ORDERS_MV
AS 
SELECT 

AVG(PS_SUPPLYCOST) AS PS_SUPPLYCOST_AVG,
AVG(PS_AVAILQTY) AS PS_AVAILQTY_AVG,
MAX(PS_COMMENT) AS PS_COMMENT_MAX

FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PARTSUPP;
