create warehouse COMPUTE_WAREHOUSE
WITH 
WAREHOUSE_SIZE=XSMALL
MAX_CLUSTER_COUNT=3
AUTO_SUSPEND=600
INITIALLY_SUSPENDED=TRUE
AUTO_RESUME=TRUE
COMMENT='This is our second warehouse'

select * from  SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

DROP WAREHOUSE COMPUTE_WAREHOUSE;